service: sls-seed-react-infra-cdn

provider:
  name: aws
  region: us-east-2
  stage: ${opt:stage, "dev"}

custom:
  hostingStackName: sls-seed-react-infra-hosting-${self:provider.stage}
  domainConfig:
    other: ${self:provider.stage}.dev.groffcole.com
    dev: apples.dev.groffcole.com
    prod: apples.groffcole.com
  domain: ${self:custom.domainConfig.${self:provider.stage}, self:custom.domainConfig.other}
  hostedZone: "groffcole.com."
  originId: ${self:service}-${self:provider.stage}-cdn-origin
  cdnIdParameterName: ${self:service}-${self:provider.stage}-cdn-id-parameter-name
  hostingBucketWebsiteUrl: ${cf:${self:custom.hostingStackName}.HostingBucketWebsiteUrl}

resources:
  # - ${file(./bucket.yml)}
  - ${file(./cloud_front.yml)}
  - ${file(./record_set.yml)}