Resources:
  HostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.hostingBucketName}
      # AccessControl: "BucketOwnerFullControl"
      # WebsiteConfiguration:
      #   IndexDocument: index.html
      #   ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
  
  # RedirectingBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: ${self:custom.redirectingBucketName}
      # AccessControl: "BucketOwnerFullControl"
      # WebsiteConfiguration:
      #   RedirectAllRequestsTo:
      #     HostName: ""
      #     Protocol: https
      #   IndexDocument: index.html
      #   ErrorDocument: index.html
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: true
  #       IgnorePublicAcls: true
  #       BlockPublicPolicy: false
  #       RestrictPublicBuckets: false

  # RedirectingBucketBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket:
  #       Ref: RedirectingBucket
  #     PolicyDocument:
  #       Statement:
  #         - Effect: "Allow"
  #           Principal: "*"
  #           Action:
  #             - "s3:GetObject"
  #           Resource: !Join ["", ["arn:aws:s3:::", Ref: RedirectingBucket, "/*"]]

Outputs:
  HostingBucketName:
    Value:
      Ref: HostingBucket
  # HostingBucketArn:
  #   Value:
  #     Fn::GetAtt: [HostingBucket, Arn]
  HostingBucketDomainName:
    Value:
      Fn::GetAtt: [HostingBucket, DomainName]
  # BucketDualStackDomainName:
  #   Value:
  #     Fn::GetAtt: [HostingBucket, DualStackDomainName]
  # BucketRegionalDomainName:
  #   Value:
  #     Fn::GetAtt: [HostingBucket, RegionalDomainName]
  # BucketWebsiteURL:
  #   Value:
  #     Fn::GetAtt: [HostingBucket, WebsiteURL]
  # BucketSplitWebsiteURL:
  #   Value:
  #     Fn::Select:
  #       - "1"
  #       - Fn::Split:
  #         - "://"
  #         - Fn::GetAtt: [HostingBucket, WebsiteURL]
  # RedirectingBucketWebsiteUrl:
  #   Value:
  #     Fn::Select:
  #       - "1"
  #       - Fn::Split:
  #         - "://"
  #         - Fn::GetAtt: [RedirectingBucket, WebsiteURL]