service:
  name: sls-seed-react-infra-hosting

provider:
  name: aws
  region: us-east-2
  stage: ${opt:stage, "dev"}

custom:
  hostingBucketName: ${self:service}-${self:provider.stage}-hosting-bucket

resources:
  - ${file(./bucket.yml)}