service: sls-seed-react-infra

provider:
  name: aws
  region: us-east-2
  stage: ${opt:stage, "dev"}


resources:
  Resources:
    SomeBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sls-seed-react-infra-${self:provider.stage}-3
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
