service: sls-seed-react-infra

provider:
  name: aws
  region: us-east-2
  stage: ${opt:stage, "dev"}

resources:
  Resources:
    HostingBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          IgnorePublicAcls: true
          BlockPublicPolicy: false
          RestrictPublicBuckets: false

    HostingBucketBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: HostingBucket
        PolicyDocument:
          Statement:
            - Effect: "Allow"
              Principal: "*"
              Action:
                - "s3:GetObject"
              Resource: !Join ["", ["arn:aws:s3:::", Ref: HostingBucket, "/*"]]

    HostingBucketCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - CustomOriginConfig:
                DomainName:
                  Fn::GetAtt: [HostingBucket, WebsiteURL]
                Id: !Join ["", ["S3-Website-", Fn::GetAtt: [HostingBucket, WebsiteURL]]]

# sls-seed-react-infra-cole2.s3-website.us-east-2.amazonaws.com
# S3-Website-sls-seed-react-infra-cole2.s3-website.us-east-2.amazonaws.com